### ISSUE TITLE
Merge does not work

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/breizorro#23]
Getting
```
Traceback (most recent call last):
  File "/home/bhugo/LunarPolarimetry/venv/bin/breizorro", line 5, in <module>
    main()
  File "/home/bhugo/LunarPolarimetry/venv/lib/python3.8/site-packages/breizorro/breizorro.py", line 251, in main
    mask_image += fits[0]
numpy.core._exceptions.UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float32') to dtype('bool') with casting rule 'same_kind'
```
... why are we adding masks --- these are binaries - it is better to just or them...

**Comment by bennahugo** [comment]
While I'm at it I will add an option to and (in other words create ever more restictive masks). I need this to clean the limb of the S-band moon where I create a torus mask with another program
