### ISSUE TITLE
Request for an option to create an empty mask and merge a region file all at once

### ISSUE THREAD

**Issue by Victoria-Samboco** [ratt-ru/breizorro#25]
I want to use breizorro to create masks from region files. 

Theres an option to create an empty mask ```breizorro -m mask_test```, then I have to merge the region file to the empty mask 

```breizorro -m mask_test --merge sun_region_0.reg -o mask_test1.fits```

When trying to do it at once does not work ....

```$ breizorro -r 1671435077_sdp_l0_1024ch_GRS1747-312-MFS-image.fits -t 99999999999999999999999999999  --merge sun_region_0.reg -o mask_test2.fits```

and returns the error 
````
breizorro.breizorro - 2023-03-23 16:01:06,231 INFO - Welcome to breizorro
breizorro.breizorro - 2023-03-23 16:01:06,267 INFO - Version: 0.1.1
breizorro.breizorro - 2023-03-23 16:01:06,267 INFO - Usage: breizorro --help
breizorro.breizorro - 2023-03-23 16:01:06,268 INFO - Reading 1671435077_sdp_l0_1024ch_GRS1747-312-MFS-image.fits data
breizorro.breizorro - 2023-03-23 16:01:06,333 INFO - Generating mask using threshold 1e+29
breizorro.breizorro - 2023-03-23 16:01:06,333 INFO - Generating noise map
breizorro.breizorro - 2023-03-23 16:01:07,893 INFO - Median noise value is 2.4002554710023105e-05
WARNING: FITSFixedWarning: 'datfix' made the change 'Set MJD-OBS to 59932.366843 from DATE-OBS'. [astropy.wcs.wcs]
breizorro.breizorro - 2023-03-23 16:01:08,002 INFO - Reading /home/samboco/solarkat/SUN_IMAGING_STEPS/obs2/region_files/sun_region_0.reg data
breizorro.breizorro - 2023-03-23 16:01:08,004 INFO - Merging in 1 regions from /home/samboco/solarkat/SUN_IMAGING_STEPS/obs2/region_files/sun_region_0.reg
Traceback (most recent call last):
  File "/home/samboco/Virtual_enviroments/breizorro_env/bin/breizorro", line 5, in <module>
    main()
  File "/home/samboco/Virtual_enviroments/breizorro_env/lib/python3.8/site-packages/breizorro/breizorro.py", line 255, in main
    add_regions(mask_image, regs, wcs)
  File "/home/samboco/Virtual_enviroments/breizorro_env/lib/python3.8/site-packages/breizorro/breizorro.py", line 115, in add_regions
    mask_image += reg.to_mask().to_image(mask_image.shape)
numpy.core._exceptions.UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('bool') with casting rule 'same_kind'
````

***Any idea of solution for it?***

**Comment by Athanaseus** [comment]
Thank you for reporting this @Victoria-Samboco.

Here is the branch `issue-25`;
please check it out and see if it fixes this.
```
cd <path to your breizorro repo>
git checkout issue-25
pip install -U ./
```

**Comment by Victoria-Samboco** [comment]
> Thank you for reporting this @Victoria-Samboco.
> 
> Here is the branch `issue-25`; please check it out and see if it fixes this.
> 
> ```
> cd <path to your breizorro repo>
> git checkout issue-25
> pip install -U ./
> ```

Okay, thanks @Athanaseus I will check and send you feedback.

**Comment by Victoria-Samboco** [comment]
> Thank you for reporting this @Victoria-Samboco.
> 
> Here is the branch `issue-25`; please check it out and see if it fixes this.
> 
> ```
> cd <path to your breizorro repo>
> git checkout issue-25
> pip install -U ./
> ```

Thank you @Athanaseus it worked.
